### ISSUE TITLE
Streaming chunks of binary (float32) audio samples over websockets... a good idea in theory?

### ISSUE THREAD

**Issue by ukaj808** [GoogleChromeLabs/web-audio-samples#322] opened 2023-05-21 19:15 UTC
Hey!

My name is Fiz and Im working on a side project of mine that's using the web audio api. I'd like to "live-stream" music to multiple people in a room. I've looked into quite a few ways to approach this... One of which was simply hosting the audio file on my webserver and giving the path to the audio file directly into the src of the audio element. Using an internal timer in my websocket server, I could send the current time to the clients browser and scrub to the correct time. Using some clever logic I could ensure that all the people in the room are synced up. 

For one reason or another; I opted to use a _cleaner_ approach of live streaming using the web socket api. 

On my websocket server I have a WAV file whose raw audio data is formatted in little-endian, 32-bit, floating point decimal values. I'd like send chunks of this audio data in sizes and intervals that align with the metadata of the song. For example, an audio file with a 384,000 byterate, I send 384,000 bytes of audio every 1 second. On the client side, I'd like to stitch these chunks back together and play it back to the user.

After doing quite a bit of research into the web audio API and your articles; It seems to me that there is a nice way to implement this.

I'll use one shared array buffer in the fashion of a ring buffer. Ill use one web worker that will listen on the websocket for the audio data and place it into the ring buffer and one audio worklet node that will read from the ring buffer and put the samples into the output. This seems ideal since all the audio processing will be done outside the main thread; and nothing theoretically can block audio data from coming in (worker thread) and audio data from being processed (audio worklet thread).

My understanding of the audio worklet node is that the code in the process callback needs to run within a certain time frame or else we risk the audio having glitches. With this in mind; I opted for a modified "reader-writer" synchronization pattern where the reader (audio worklet node) will never be blocked from reading from the ring buffer. I'd like to think I can write this in such a way that will result in a perpetual cat and mouse between the reader and writer so as not to sacrifice the performance of the process callback. I imagine if the process callback has to wait for a lock to be given back from the worker that it would result in glitches. 

Since the audio data is already in float32 pcm format (floats between -1.0 and 1.0); this should just work out the box... but its not :( I can hear the song but theres alot static and the song is slowed down... Maybe static isnt the right word for it; but it sounds messed up.

I was hoping your team could find any holes in my logic that would help point me in the right direction to fixing my issue (: Apologies in advance if this was the wrong medium to reach out through.

// Abstraction of audio playback
https://github.com/ukaj808/aux.link/blob/master/static/scripts/aux-audio-player.js

// The websocket worker
https://github.com/ukaj808/aux.link/blob/master/static/scripts/workers/aux-audio-worker-ws-impl.js

// The audio worklet node
https://github.com/ukaj808/aux.link/blob/master/static/scripts/workers/aux-audio-worklet.js

Fiz

**Comment by samson-sham** [comment] 2023-05-22 13:16
I think the issue is with the processing rate of AudioWorklet. I encountered the opposite version of your case, where I have a complete buffer to be mixed into AudioWorklet, but the processing rate is too high that the buffer were immediately being consumed resulting in a short burst of audio playback. I turn out to use the deprecated scriptprocessor, which can playback the audio buffer without issue.

**Comment by hoch** [comment] 2023-05-23 00:48
Can we listen to your resulting audio with problems? As @samson-sham suggested, it does look like more of a sample rate issue, but less of buffer underruns.

**Comment by ukaj808** [comment] 2023-05-23 16:16
> Can we listen to your resulting audio with problems? As @samson-sham suggested, it does look like more of a sample rate issue, but less of buffer underruns.

Yes of course! I've included recordings of the problem audio and the original.

[examples.zip](https://github.com/GoogleChromeLabs/web-audio-samples/files/11546381/examples.zip)

**Comment by mjwilson-google** [comment] 2023-05-24 20:31
Thank you for the examples.  After listening to and looking at the waveforms, I think that some of the bytes for each floating-point sample may be going to the wrong channel, or may be in the wrong order.
I didn't look deeply into the specific code, but common causes of this kind of problem are reading and writing endieness being different, reading and writing interleaving of samples being different, or by not having a way to tell when the first byte of a sample starts.

**Comment by ukaj808** [comment] 2023-06-29 16:32
@mjwilson-google Thanks for the tip; I went back and rewrote my sample parsing logic and got it to work. I was incorrectly parsing the interleaved samples!

**Comment by mjwilson-google** [comment] 2023-06-29 17:23
Good to hear it's working!  I'll close the issue.

**Closed by mjwilson-google** 2023-06-29 17:23 UTC
Labels: type:question, P3

**Comment by fallais** [comment] 2026-04-02 06:48
@mjwilson-google : you saved more people than you think ! ;)
