### ISSUE TITLE
AudioWorkletRecorder demo is broken

### ISSUE THREAD

**Issue by hoch** [GoogleChromeLabs/web-audio-samples#261] opened 2022-11-14 18:12 UTC
Reproduction steps:
1. Go to https://googlechromelabs.github.io/web-audio-samples/audio-worklet/migration/worklet-recorder/
2. Change maxFrameCount: context.sampleRate*10 to  maxFrameCount: context.sampleRate*100 to record more than 10s in app.js
3. Record > 30s of audio playing from another tab
4. Playback the audio. You'll see the audio is distorted after 30s

At least this is reproducible on Mac.

**Comment by hoch** [comment] 2022-11-14 18:25
The important step is 3. The distortion happens only when the tab goes background.

**Comment by chrisguttandin** [comment] 2022-11-22 19:54
Could this be the same bug as reported [here](https://bugs.chromium.org/p/chromium/issues/detail?id=995124)?

**Comment by hoch** [comment] 2022-11-23 17:05
I have a fix under development - but to answer your question, this example uses AW not MediaRecorder.

**Comment by chrisguttandin** [comment] 2022-11-24 10:11
Sorry, my bad. I linked to the wrong bug. I meant this one. https://bugs.chromium.org/p/chromium/issues/detail?id=1016104

**Comment by yefim** [comment] 2023-02-07 23:40
None of the recording demos work

**Comment by hoch** [comment] 2023-02-08 00:00
@yefim Can you elaborate a bit more? What was not working?

**Comment by yefim** [comment] 2023-02-13 00:13
1. Go to https://googlechromelabs.github.io/web-audio-samples/audio-worklet/migration/worklet-recorder/
2. Click start recording like 2 or 3 times
3. Click stop recording
4. Watch it do nothing

What I expect:

I want to be able to preview and download my recording

**Comment by TenghuiZhang** [comment] 2023-04-19 23:11
@yefim Hi, I was not able to reproduce this issue. Could you help me provide some details or video recording relate to the issue which you mention?

**Comment by TenghuiZhang** [comment] 2023-05-24 17:43
Since this issue seems resolve, I am going to close this issue. Feel free to reopen it if there is any broken demo or link.

**Closed by TenghuiZhang** 2023-05-24 17:43 UTC
Labels: type:bug, P1

**Comment by yefim** [comment] 2024-01-18 08:00
Here's a video of the recorder demo not working. I recorded myself speaking but cannot play it back. https://streamable.com/3w2gsy
